// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEBOBSKbDqvVwTz4s4K3AQDzYBByJHlSg',
    appId: '1:659652891796:web:cfe43fad3ce7712328d081',
    messagingSenderId: '659652891796',
    projectId: 'book-my-game-a9b76',
    authDomain: 'book-my-game-a9b76.firebaseapp.com',
    storageBucket: 'book-my-game-a9b76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEBOBSKbDqvVwTz4s4K3AQDzYBByJHlSg',
    appId: '1:659652891796:android:68b69be5a40bc0ca28d081',
    messagingSenderId: '659652891796',
    projectId: 'book-my-game-a9b76',
    storageBucket: 'book-my-game-a9b76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASt31yyM1uKfvcsk0cZ1ESBUR1vwetH3U',
    appId: '1:659652891796:ios:0b37d1af17ea33c928d081',
    messagingSenderId: '659652891796',
    projectId: 'book-my-game-a9b76',
    storageBucket: 'book-my-game-a9b76.firebasestorage.app',
    iosBundleId: 'com.example.bookMyGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASt31yyM1uKfvcsk0cZ1ESBUR1vwetH3U',
    appId: '1:659652891796:ios:0b37d1af17ea33c928d081',
    messagingSenderId: '659652891796',
    projectId: 'book-my-game-a9b76',
    storageBucket: 'book-my-game-a9b76.firebasestorage.app',
    iosBundleId: 'com.example.bookMyGame',
  );
}
